### ISSUE TITLE
ipfs.add() throws IOException

### ISSUE THREAD

**Issue by mariosk** [ipfs/java-ipfs-api#34]
It seems that the latest pubsub implementation broke the ipfs.add() functionality:
MerkleNode addResult = ipfs.add(new NamedStreamable.FileWrapper(path.toFile()));

The above statement leads to the following exception:

IOException contacting IPFS daemon.
Trailer: [X-Stream-Error] {"Message":"merkledag node was not a directory or shard","Code":0}

java.lang.RuntimeException: IOException contacting IPFS daemon.
Trailer: [X-Stream-Error] {"Message":"merkledag node was not a directory or shard","Code":0}

	at io.ipfs.api.IPFS.get(IPFS.java:594)
	at io.ipfs.api.IPFS.retrieve(IPFS.java:573)
	at io.ipfs.api.IPFS.retrieveAndParse(IPFS.java:555)
	at io.ipfs.api.IPFS.retrieveMap(IPFS.java:551)
	at io.ipfs.api.IPFS.ls(IPFS.java:94)
	at com.ipfs.server.cratesapp.App.addFolderToIPFS(App.java:21)
	at com.ipfs.server.cratesapp.App.lambda$0(App.java:34)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at com.ipfs.server.cratesapp.App.walkFolderFiles(App.java:32)
	at com.ipfs.server.cratesapp.App.main(App.java:51)
Caused by: java.io.IOException: Server returned HTTP response code: 500 for URL: http://127.0.0.1:5001/api/v0/ls/QmaQqhi4FjmeRqKoTvEcJMHCKxPZCbSShZE8G5TdTdwh4e
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1876)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at io.ipfs.api.IPFS.get(IPFS.java:582)
	... 18 more

Also relevant unit test is failed:

directoryTest(io.ipfs.api.APITest)  Time elapsed: 0.594 sec  <<< ERROR!
java.lang.RuntimeException:
IOException contacting IPFS daemon.
Trailer: [X-Stream-Error] {"Message":"merkledag node was not a directory or shard","Code":0}

**Comment by ianopolous** [comment]
Apologies, that's fixed now in master. All tests are green.
