### ISSUE TITLE
Android Looping on ipfs.add(file)

### ISSUE THREAD

**Issue by BenKrarup** [ipfs/java-ipfs-api#36]
Hi,

Have written - 

NamedStreamable.ByteArrayWrapper ipfsFile = new NamedStreamable.ByteArrayWrapper(usr + ".txt", userJSON.toString().getBytes());
MerkleNode addFile = ipfs.add(ipfsFile);

As given in the README but it goes to the looper class and just loops forever causing the app to crash on MerkleNode addFile = ipfs.add(ipfsFile); have tried with a FileWrapper as well. Can't see anything in the source code of why this would happen. 

Any help?

Thanks.

**Comment by BenKrarup** [comment]
It's getting the error - 
FATAL EXCEPTION: main
                                                                                  Process: benkrarup.ethereum.messagingdapp, PID: 24710
                                                                                  java.lang.NoClassDefFoundError: Failed resolution of: Ljava/nio/file/Paths;
                                                                                      at io.ipfs.api.IPFS.add(IPFS.java:85)
                                                                                      at io.ipfs.api.IPFS.add(IPFS.java:70)
                                                                                      at benkrarup.ethereum.messagingdapp.RegisterActivity$1.onClick(RegisterActivity.java:91)
                                                                                      at android.view.View.performClick(View.java:5610)
                                                                                      at android.view.View$PerformClick.run(View.java:22265)
                                                                                      at android.os.Handler.handleCallback(Handler.java:751)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                      at android.os.Looper.loop(Looper.java:154)
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
                                                                                   Caused by: java.lang.ClassNotFoundException: Didn't find class "java.nio.file.Paths" on path: DexPathList[[zip file "/data/app/benkrarup.ethereum.messagingdapp-2/base.apk"],nativeLibraryDirectories=[/data/app/benkrarup.ethereum.messagingdapp-2/lib/x86, /data/app/benkrarup.ethereum.messagingdapp-2/base.apk!/lib/x86, /system/lib, /vendor/lib]]
                                                                                      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                                      at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                                                      at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                      at io.ipfs.api.IPFS.add(IPFS.java:85) 
                                                                                      at io.ipfs.api.IPFS.add(IPFS.java:70) 
                                                                                      at benkrarup.ethereum.messagingdapp.RegisterActivity$1.onClick(RegisterActivity.java:91) 
                                                                                      at android.view.View.performClick(View.java:5610) 
                                                                                      at android.view.View$PerformClick.run(View.java:22265) 
                                                                                      at android.os.Handler.handleCallback(Handler.java:751) 
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                                      at android.os.Looper.loop(Looper.java:154) 
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:6077) 
                                                                                      at java.lang.reflect.Method.invoke(Native Method) 
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866) 
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)

**Comment by BenKrarup** [comment]
Have found the problem - java.nio.file not included on android API 25 and lower.
