### ISSUE TITLE
go-ipfs 0.4.11-rc1: Crashing error when adding file

### ISSUE THREAD

**Issue by ESchouten** [ipfs/java-ipfs-api#41]
Version: 1.1.1
Incompatibility with go-ipfs 0.4.11.rc1

java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
	at io.ipfs.api.MerkleNode.fromJSON(MerkleNode.java:55)
	at io.ipfs.api.IPFS.lambda$add$1(IPFS.java:89)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at io.ipfs.api.IPFS.add(IPFS.java:90)
	at io.ipfs.api.IPFS.add(IPFS.java:70)

**Comment by ianopolous** [comment]
I'm trying to verify that this isn't a regression in IPFS itself, but at the moment my ipfs build is erroring with go-1.9. As soon as I can build it and reproduce I'll get back to you.

**Comment by ianopolous** [comment]
I think it is a regression in IPFS itself. I will post an issue.

**Comment by ianopolous** [comment]
See https://github.com/ipfs/go-ipfs/issues/4248

**Comment by ianopolous** [comment]
Turns it isn't a regression, but a planned change, which eventually will be a breaking change with the other usages. I will rework our class structure.

**Comment by ianopolous** [comment]
This is fixed in master now.
