### ISSUE TITLE
go-ipfs Version v0.4.13 for windows 64bit

### ISSUE THREAD

**Issue by jyrkioraskari** [ipfs/java-ipfs-api#54]
Hi,

The Java API library functions  fine with the 28/09/2017 version of the go-ipfs client. Now when I updated that to the current version ( Version v0.4.13 for windows 64bit) the JSON messages of the server do not seem to be compatible with the Java API (java-ipfs-api v1.1.1) library anymore.

My code:
NamedStreamable.ByteArrayWrapper file = new NamedStreamable.ByteArrayWrapper(guid,
                    r1.getCanonicalString().getBytes());
            MerkleNode node = ipfs.add(file);
Gets the following error now:

java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
	at io.ipfs.api.MerkleNode.fromJSON(MerkleNode.java:55)
	at io.ipfs.api.IPFS.lambda$add$1(IPFS.java:89)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1380)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at io.ipfs.api.IPFS.add(IPFS.java:90)
	at io.ipfs.api.IPFS.add(IPFS.java:70)

Kind regards,

J.

**Comment by ianopolous** [comment]
Have you tried the latest release (1.2.0)?

**Comment by jyrkioraskari** [comment]
Hi,

Thank you! It works.  Could you kindly update the documentation (the version reference) on the page:
https://github.com/ipfs/java-ipfs-api
J.
