### ISSUE TITLE
Failure with recursive add with binary in sub directory

### ISSUE THREAD

**Issue by tdiesler** [ipfs/java-ipfs-api#79]
When adding a tree like this

```
$ ipfs add -r src/test/resources/html
added QmVts3YjmhsCSqMv8Thk1CCy1nnpCbqEFjbkjS7PEzthZE html/README.html
added QmYpbSXyiCTYCbyMpzrQNix72nBYB8WRv6i39JqRc8C1rx html/chap/ch01.html
added QmT1cVKZQPvKhS8Rg9ek7UgThwFC8gC6gAJBiRwMKMnYyg html/css/default.css
added QmaMgvGJjZU511pzH1fSwh9RRnKckyujoRxVeDSEaEGM5N html/img/logo.png
added QmeaY5WQKs3iB5UrgobERnTamHwJYMcCLRWhHK42KtVt1b html/chap
added QmfPRsChuVCsnN4PGLaDCngvjqCoc9KGkxea4hgiq6qitk html/css
added QmYhaNnLGtFDEc559T9bVkqYqaXLGojMWDzVqjFZgrmnCi html/img
added QmWVMRbFTrA6pMhsfXzsyoWqmrhy5FPd4VitfX79R5bguw html
```

I see the java client fail like this

```
java.lang.IllegalStateException: Remote IPFS error: http: invalid Read on closed Body
	at io.ipfs.api.MerkleNode.fromJSON(MerkleNode.java:74)
	at io.ipfs.api.IPFS.lambda$0(IPFS.java:91)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at io.ipfs.api.IPFS.add(IPFS.java:92)
	at io.ipfs.api.IPFS.add(IPFS.java:78)
	at io.ipfs.api.IPFS.add(IPFS.java:74)
	at io.ipfs.api.IPFS.add(IPFS.java:70)
	at io.ipfs.api.RecursiveAddTest.testAdd(RecursiveAddTest.java:21)
```

This is caused by `html/img/logo.png`

Here is a PR that should help to reproduce this: https://github.com/ipfs/java-ipfs-api/pull/80

**Comment by tdiesler** [comment]
This still seems to work with 0.4.13 but fails with 0.4.14 and above

**Comment by tdiesler** [comment]
This is a blocking issue for our Blockchain + IPFS effort

**Comment by tdiesler** [comment]
This seems to be a problem with the server side impl. I replaced all of the multipart and named stream impl with Apache HttpClient and byte[]. It now does not fail as reliably any more, but it still fails ca. 50% of the time. The cmd line client must somehow construct/send the multipart request in a different way, such that the server reliably accepts it - I'm puzzled.

Any idea, any one?

https://github.com/tdiesler/java-ipfs-api/blob/ghi79/src/test/java/io/ipfs/api/RecursiveAddTest.java#L69

**Comment by tdiesler** [comment]
Done.

PR #91 replaces the existing Multipart implementation with Apache HttpClient. I believe the problem was with an incorrect implementation of chunked encoding, which is indeed not trivial to do. 

This now pulls in additional dependencies

```
[tdiesler@macbook java-ipfs-api]$ mvn dependency:tree
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building java-ipfs-api v1.2.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ api ---
[INFO] io.ipfs:api:jar:v1.2.1-SNAPSHOT
[INFO] +- com.github.multiformats:java-multiaddr:jar:v1.3.0:compile
[INFO] |  +- com.github.multiformats:java-multibase:jar:v1.0.0:compile
[INFO] |  +- com.github.multiformats:java-multihash:jar:v1.1.0:compile
[INFO] |  \- com.github.ipld:java-cid:jar:v1.1.0:compile
[INFO] +- org.apache.httpcomponents:httpmime:jar:4.5.6:compile
[INFO] |  \- org.apache.httpcomponents:httpclient:jar:4.5.6:compile
[INFO] |     +- org.apache.httpcomponents:httpcore:jar:4.4.10:compile
[INFO] |     +- commons-logging:commons-logging:jar:1.2:compile
[INFO] |     \- commons-codec:commons-codec:jar:1.10:compile
[INFO] +- junit:junit:jar:4.12:test
[INFO] \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```

and will likely break the non-maven build. However, it removes the maintenance cost for a correct multipart implementation and perhaps more importantly should work with very large files in directory structures.

Tested with 
```
> ipfs daemon --enable-pubsub-experiment &
> mvn clean install

Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.799 sec - in io.ipfs.api.IPFSAddTest
Tests run: 36, Failures: 0, Errors: 0, Skipped: 2, Time elapsed: 21.839 sec - in io.ipfs.api.APITest
```

**Comment by tdiesler** [comment]
Thanks.

This is now out of date
