### ISSUE TITLE
I don't understand the constructor

### ISSUE THREAD

**Issue by matshenricson** [ipfs/java-ipfs-api#8]
I started using the API with 127.0.0.1 as address to the IPFS constructor, and all worked fine, because I had my local IPFS node up, of course. But I'd like to try accessing another node, so I changed to a different IP address, and turned off my local node, and got the exception below. I used this constructor argument:

new IPFS("/ip4/ipfs.innovandalism.eu/tcp/5001")

It turns out this wouldn't work anyway, because innovandalism.eu doesn't allow the kind of access I was thinking about, but why would the Java API access localhost if I set it to connect to another machine?

-----------------------------------------------
Connected to the target VM, address: '127.0.0.1:45596', transport: 'socket'

Connection refused
java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1168)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1104)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:998)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:932)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1282)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1257)
	at org.ipfs.api.Multipart.<init>(Multipart.java:27)
	at org.ipfs.api.IPFS.add(IPFS.java:54)
	at org.ipfs.api.IPFS.add(IPFS.java:50)
	at xyztr.IPFSProxy$.send(IPFSProxy.scala:26)
...

**Comment by ianopolous** [comment]
That constructor is taking a multiaddress (https://github.com/jbenet/multiaddr)
/ip4 is expecting an ipv4 address after it.
It's a bug in MultiAddress that it doesn't fail earlier but that won't help you here. As far as I can tell a multiaddress isn't allowed to take a domain name. If you use the constructor with the host and the port it should work.

**Comment by ianopolous** [comment]
Despite the spec being unclear, I've double checked the source and the Java version does tolerate that and will do a dns lookup to get the ip address. So what you've done should actually work. How do you know it's trying to talk to localhost?
