### ISSUE TITLE
NPE in simple recursive ipfs add scenario

### ISSUE THREAD

**Issue by tdiesler** [ipfs/java-ipfs-api#95]
```
Tests run: 5, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.241 sec <<< FAILURE! - in io.ipfs.api.SimpleAddTest
testRecursiveOnlyHash(io.ipfs.api.SimpleAddTest)  Time elapsed: 0.065 sec  <<< ERROR!
java.lang.NullPointerException
	at io.ipfs.api.SimpleAddTest.testRecursiveOnlyHash(SimpleAddTest.java:87)

testRecursive(io.ipfs.api.SimpleAddTest)  Time elapsed: 0.008 sec  <<< ERROR!
java.lang.NullPointerException
	at io.ipfs.api.SimpleAddTest.testRecursive(SimpleAddTest.java:75)
```

**Comment by ianopolous** [comment]
This and the underlying multipart bug are fixed in master now
